### ISSUE TITLE
Created a pim-demo-element (+ link to PDF)

### ISSUE THREAD

**Issue by warpech** [Juicy/x-breadcrumb#6]
I created another demo, consisting of files:
- `pim-demo.html`
- `pim-demo-element.html`

That simulates the way we want to use `x-crumbs`. It shows how the selection & searching logic will be applied from the outside.

The external logic controls:
- what are the crumbs on screen
- what is displayed in the dropdown
- what happens when you enter a search query in the dropdown
- what happens when you click on an item in the dropdown

The attached PDF file shows the planned usage of the elements:
- [PIM breadcrumb usage v3.pdf](https://github.com/Juicy/x-breadcrumb/files/59225/PIM.breadcrumb.usage.v3.pdf)

**Comment by warpech** [comment]
I made a hack in https://github.com/Juicy/x-breadcrumb/blob/master/x-crumb.html#L310 to show dropdowns always in expanded state, because I was not able to get them to work otherwise in `pim-demo-element.html`.

``` css
    ::content .options {
      /**height: 0;temporarily disabled by @warpech because I was not able to expand dropdown in pim-demo-element.html*/
      display: block;
      width: 108%;
      overflow: hidden;
    }
```
